language: python
os:
  - linux
python:
  - 2.7
  - 3.3
  # TODO: activate (travis bug)
  # - 3.4
  - 3.5
sudo: false
env:
  - TOXENV="py${PYTHON_VERSION//./}"
install:
  - pip install tox coveralls
script: tox
deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: OQ5K2lulNHI5G4SdKkdsvAGPPBTsa35y+QwQ7HbwEdEXGJvIxth8dchog/zDO+m0tTd+kuSxkuzOUpX5k2YBtr3QxwQ148ts2xKIooULN695LXwKOhfmk7HoI4JbsUxgu/Rx+drfQs09DPrW/ViBGtKHlQ8LuR6hO8D3leMCwF5+iK9pZIoO8x6iZp4ytDJZxLOHBg5prTzJP3TMKtF458JRkAm3eU5SHidi4PiuUCjpn1BTnpx+vsleQVNkA0mVtLIY8uwC9mtLknjBCCywhntNvNJia2MwraPmNArfY+kwtAJwd4sLu/iCQ0udMJNve0/kL0BsuEhzJpSd+3dGhQbPi9LtIwBu4AivBHCGJXgvPVLt0/3iFg+iGyeFtB1/zqo31psCr+Xbkt/8zjgBSAFY3rqYWQlFEvpePVLp7QP1ql0Vis08592nNRPW9WYkhDx6AKJbAbpngKUnZXQ8Xm0X4pZ83wX+noxzijSjvlVCaGYe7K1t6cgVp1VhROguxbXbjSYcGrbg8tlDqF83H18cDdyzi1D8y+1JOqZ/kwncqzmQRxezVA9+w/Ljbq4OCGpYdDsz1SGUq/YUEr6V+E0Eu3OR/mCePI6Mqjmchr4OFdh4cZ0OpxGpasUhwiLDBv1xE6D7SGlb4rkXgZ9dUxltDPIc+7erU0dMMNCfkp4=
